general.live_config_reload=true

[window]

opacity = 0.75

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "ZedMono Nerd Font Mono"
bold.family = "ZedMono Nerd Font Mono"
italic.family = "ZedMono Nerd Font Mono"
bold_italic.family = "ZedMono Nerd Font Mono"

size = 12.5

