# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cbdd3cdb-ddc0-4215-9a0b-ecf960a3ad16";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/mount/E:" =
    { device = "/dev/disk/by-uuid/f4328487-3c67-489d-bad8-bdeea89661c8";
      fsType = "ext4";
    };

  fileSystems."/snap/bare/5" =
    { device = "/var/lib/snapd/snaps/bare_5.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/snap/core20/2496" =
    { device = "/var/lib/snapd/snaps/core20_2496.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/snap/core20/2501" =
    { device = "/var/lib/snapd/snaps/core20_2501.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/snap/gtk-common-themes/1535" =
    { device = "/var/lib/snapd/snaps/gtk-common-themes_1535.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/snap/snapd/23545" =
    { device = "/var/lib/snapd/snaps/snapd_23545.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/snap/snapd/23771" =
    { device = "/var/lib/snapd/snaps/snapd_23771.snap";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/200ba35a-54dc-461c-b351-9d9ed94b9dbf";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
